### ISSUE TITLE
Helm templates require modifications to work with helm-secrets

### ISSUE THREAD

**Issue by jakereps** [zendesk/helm-secrets#77]
Awesome tool! Ran into an issue while implementing it that I thought I'd bring up. I haven't been able to find a related issue (open or closed), but feel free to close this if it's been answered before!

Helm itself allows values to be simple go templates, not enclosed in quotation marks. It actually templates them out in this this way using `helm create`. Adding `helm-secrets` to an existing project with this requirement introduces a lot of unnecessary work.

I've have a minimal example to show what I mean:

```yaml
# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: example
  labels:    
    app: {{ include "mychart.name" . }}
    chart: {{ include "mychart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  foo: bar
```

```bash
$ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
$ helm secrets lint . -f templates/secrets.yaml
Not encrypted: templates/secrets.yaml
Error: failed to parse templates/secrets.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Release.Name":interface {}(nil)}
```

Required to work with `helm-secrets`
```yaml
# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: example
  labels:
    app: '{{ include "mychart.name" . }}'
    chart: '{{ include "mychart.chart" . }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  foo: bar
```

```bash
$ helm secrets lint . -f templates/secrets.yaml
Not encrypted: templates/secrets.yaml
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

---
System Specs
```
# OS
MacOS 10.14.1 (18B75)

# Helm
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

# Helm Plugins
NAME    VERSION DESCRIPTION
secrets 2.0.0   This plugin provides secrets values encryption for Helm charts secure storing
```

**Comment by igoooor** [comment]
I have the same issue, but with one case I'm not able to fix:

```
apiVersion: v1
kind: Secret
metadata:
  name: example
  labels:
    {{- include "mychart.labels" . | indent 4 }}
type: Opaque
stringData:
  foo: bar
```

with `mychart.labels` being a set of key/values

Here, with or without quotes, it just won't work.
Anyone knows how to make it work?
